### ISSUE TITLE
Typo at 'Programmatically navigate' quiz section

### ISSUE THREAD

**Issue by hyfydistro** [uidotdev/react-router-v5-course#5]
Hello, I would like to report a typo on the quiz page. It is a missing closing apostrophe. :)
 
![typo-00](https://user-images.githubusercontent.com/24542308/142750884-e76d8070-f062-46e3-8b06-b3273203b9c7.png)

**Comment by hyfydistro** [comment]
There is actually two. In the option list, 
1. on the first row
2. on the 3rd row

**Comment by tylermcginnis** [comment]
Fixed. Thank you!
